# Generated by Django 5.1.1 on 2024-09-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lauthor',
            new_name='author',
        ),
    ]
